copy_figures: copy_zm copy_zp

copy_zm:
	for i in 0.0 0.25 1.0 2.0 4.0 8.0; do for j in 0 3 9; do cp ~/Doctorado/Simulaciones/figuras/fig3/B$$i\_y_Hc0.$$j\_kperp0_zm.png .; done; done

copy_zp:
	for i in 0.0 0.25 1.0 2.0 4.0 8.0; do for j in 0 3 9; do cp ~/Doctorado/Simulaciones/figuras/fig3/B$$i\_y_Hc0.$$j\_kperp0_zp.png .; done; done
